/*
ncloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDomain200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDomain200Response{}

// GetDomain200Response struct for GetDomain200Response
type GetDomain200Response struct {
	Content []GetDomain200ResponseContentInner `json:"content,omitempty"`
}

// NewGetDomain200Response instantiates a new GetDomain200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomain200Response() *GetDomain200Response {
	this := GetDomain200Response{}
	return &this
}

// NewGetDomain200ResponseWithDefaults instantiates a new GetDomain200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomain200ResponseWithDefaults() *GetDomain200Response {
	this := GetDomain200Response{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *GetDomain200Response) GetContent() []GetDomain200ResponseContentInner {
	if o == nil || IsNil(o.Content) {
		var ret []GetDomain200ResponseContentInner
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomain200Response) GetContentOk() ([]GetDomain200ResponseContentInner, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GetDomain200Response) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []GetDomain200ResponseContentInner and assigns it to the Content field.
func (o *GetDomain200Response) SetContent(v []GetDomain200ResponseContentInner) {
	o.Content = v
}

func (o GetDomain200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDomain200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableGetDomain200Response struct {
	value *GetDomain200Response
	isSet bool
}

func (v NullableGetDomain200Response) Get() *GetDomain200Response {
	return v.value
}

func (v *NullableGetDomain200Response) Set(val *GetDomain200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomain200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomain200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomain200Response(val *GetDomain200Response) *NullableGetDomain200Response {
	return &NullableGetDomain200Response{value: val, isSet: true}
}

func (v NullableGetDomain200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomain200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


