/*
ncloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRecord200ResponseContentInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRecord200ResponseContentInner{}

// GetRecord200ResponseContentInner struct for GetRecord200ResponseContentInner
type GetRecord200ResponseContentInner struct {
	Name *string `json:"name,omitempty"`
	Host *string `json:"host,omitempty"`
	Type *string `json:"type,omitempty"`
	Content *string `json:"content,omitempty"`
	Ttl *int64 `json:"ttl,omitempty"`
	AliasId *int64 `json:"aliasId,omitempty"`
	Id *int64 `json:"id,omitempty"`
	DomainName *string `json:"domainName,omitempty"`
	CreatedDate *int64 `json:"createdDate,omitempty"`
	ModifiedDate *int64 `json:"modifiedDate,omitempty"`
	DefaultYn *bool `json:"defaultYn,omitempty"`
	ApplyYn *bool `json:"applyYn,omitempty"`
	AliasYn *bool `json:"aliasYn,omitempty"`
	LbPlatform *string `json:"lbPlatform,omitempty"`
	LbYn *bool `json:"lbYn,omitempty"`
	DelYn *bool `json:"delYn,omitempty"`
}

// NewGetRecord200ResponseContentInner instantiates a new GetRecord200ResponseContentInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRecord200ResponseContentInner() *GetRecord200ResponseContentInner {
	this := GetRecord200ResponseContentInner{}
	return &this
}

// NewGetRecord200ResponseContentInnerWithDefaults instantiates a new GetRecord200ResponseContentInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRecord200ResponseContentInnerWithDefaults() *GetRecord200ResponseContentInner {
	this := GetRecord200ResponseContentInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetRecord200ResponseContentInner) SetName(v string) {
	o.Name = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *GetRecord200ResponseContentInner) SetHost(v string) {
	o.Host = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetRecord200ResponseContentInner) SetType(v string) {
	o.Type = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *GetRecord200ResponseContentInner) SetContent(v string) {
	o.Content = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetTtl() int64 {
	if o == nil || IsNil(o.Ttl) {
		var ret int64
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetTtlOk() (*int64, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int64 and assigns it to the Ttl field.
func (o *GetRecord200ResponseContentInner) SetTtl(v int64) {
	o.Ttl = &v
}

// GetAliasId returns the AliasId field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetAliasId() int64 {
	if o == nil || IsNil(o.AliasId) {
		var ret int64
		return ret
	}
	return *o.AliasId
}

// GetAliasIdOk returns a tuple with the AliasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetAliasIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AliasId) {
		return nil, false
	}
	return o.AliasId, true
}

// HasAliasId returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasAliasId() bool {
	if o != nil && !IsNil(o.AliasId) {
		return true
	}

	return false
}

// SetAliasId gets a reference to the given int64 and assigns it to the AliasId field.
func (o *GetRecord200ResponseContentInner) SetAliasId(v int64) {
	o.AliasId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GetRecord200ResponseContentInner) SetId(v int64) {
	o.Id = &v
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *GetRecord200ResponseContentInner) SetDomainName(v string) {
	o.DomainName = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetCreatedDate() int64 {
	if o == nil || IsNil(o.CreatedDate) {
		var ret int64
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetCreatedDateOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given int64 and assigns it to the CreatedDate field.
func (o *GetRecord200ResponseContentInner) SetCreatedDate(v int64) {
	o.CreatedDate = &v
}

// GetModifiedDate returns the ModifiedDate field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetModifiedDate() int64 {
	if o == nil || IsNil(o.ModifiedDate) {
		var ret int64
		return ret
	}
	return *o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetModifiedDateOk() (*int64, bool) {
	if o == nil || IsNil(o.ModifiedDate) {
		return nil, false
	}
	return o.ModifiedDate, true
}

// HasModifiedDate returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasModifiedDate() bool {
	if o != nil && !IsNil(o.ModifiedDate) {
		return true
	}

	return false
}

// SetModifiedDate gets a reference to the given int64 and assigns it to the ModifiedDate field.
func (o *GetRecord200ResponseContentInner) SetModifiedDate(v int64) {
	o.ModifiedDate = &v
}

// GetDefaultYn returns the DefaultYn field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetDefaultYn() bool {
	if o == nil || IsNil(o.DefaultYn) {
		var ret bool
		return ret
	}
	return *o.DefaultYn
}

// GetDefaultYnOk returns a tuple with the DefaultYn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetDefaultYnOk() (*bool, bool) {
	if o == nil || IsNil(o.DefaultYn) {
		return nil, false
	}
	return o.DefaultYn, true
}

// HasDefaultYn returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasDefaultYn() bool {
	if o != nil && !IsNil(o.DefaultYn) {
		return true
	}

	return false
}

// SetDefaultYn gets a reference to the given bool and assigns it to the DefaultYn field.
func (o *GetRecord200ResponseContentInner) SetDefaultYn(v bool) {
	o.DefaultYn = &v
}

// GetApplyYn returns the ApplyYn field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetApplyYn() bool {
	if o == nil || IsNil(o.ApplyYn) {
		var ret bool
		return ret
	}
	return *o.ApplyYn
}

// GetApplyYnOk returns a tuple with the ApplyYn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetApplyYnOk() (*bool, bool) {
	if o == nil || IsNil(o.ApplyYn) {
		return nil, false
	}
	return o.ApplyYn, true
}

// HasApplyYn returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasApplyYn() bool {
	if o != nil && !IsNil(o.ApplyYn) {
		return true
	}

	return false
}

// SetApplyYn gets a reference to the given bool and assigns it to the ApplyYn field.
func (o *GetRecord200ResponseContentInner) SetApplyYn(v bool) {
	o.ApplyYn = &v
}

// GetAliasYn returns the AliasYn field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetAliasYn() bool {
	if o == nil || IsNil(o.AliasYn) {
		var ret bool
		return ret
	}
	return *o.AliasYn
}

// GetAliasYnOk returns a tuple with the AliasYn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetAliasYnOk() (*bool, bool) {
	if o == nil || IsNil(o.AliasYn) {
		return nil, false
	}
	return o.AliasYn, true
}

// HasAliasYn returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasAliasYn() bool {
	if o != nil && !IsNil(o.AliasYn) {
		return true
	}

	return false
}

// SetAliasYn gets a reference to the given bool and assigns it to the AliasYn field.
func (o *GetRecord200ResponseContentInner) SetAliasYn(v bool) {
	o.AliasYn = &v
}

// GetLbPlatform returns the LbPlatform field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetLbPlatform() string {
	if o == nil || IsNil(o.LbPlatform) {
		var ret string
		return ret
	}
	return *o.LbPlatform
}

// GetLbPlatformOk returns a tuple with the LbPlatform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetLbPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.LbPlatform) {
		return nil, false
	}
	return o.LbPlatform, true
}

// HasLbPlatform returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasLbPlatform() bool {
	if o != nil && !IsNil(o.LbPlatform) {
		return true
	}

	return false
}

// SetLbPlatform gets a reference to the given string and assigns it to the LbPlatform field.
func (o *GetRecord200ResponseContentInner) SetLbPlatform(v string) {
	o.LbPlatform = &v
}

// GetLbYn returns the LbYn field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetLbYn() bool {
	if o == nil || IsNil(o.LbYn) {
		var ret bool
		return ret
	}
	return *o.LbYn
}

// GetLbYnOk returns a tuple with the LbYn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetLbYnOk() (*bool, bool) {
	if o == nil || IsNil(o.LbYn) {
		return nil, false
	}
	return o.LbYn, true
}

// HasLbYn returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasLbYn() bool {
	if o != nil && !IsNil(o.LbYn) {
		return true
	}

	return false
}

// SetLbYn gets a reference to the given bool and assigns it to the LbYn field.
func (o *GetRecord200ResponseContentInner) SetLbYn(v bool) {
	o.LbYn = &v
}

// GetDelYn returns the DelYn field value if set, zero value otherwise.
func (o *GetRecord200ResponseContentInner) GetDelYn() bool {
	if o == nil || IsNil(o.DelYn) {
		var ret bool
		return ret
	}
	return *o.DelYn
}

// GetDelYnOk returns a tuple with the DelYn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200ResponseContentInner) GetDelYnOk() (*bool, bool) {
	if o == nil || IsNil(o.DelYn) {
		return nil, false
	}
	return o.DelYn, true
}

// HasDelYn returns a boolean if a field has been set.
func (o *GetRecord200ResponseContentInner) HasDelYn() bool {
	if o != nil && !IsNil(o.DelYn) {
		return true
	}

	return false
}

// SetDelYn gets a reference to the given bool and assigns it to the DelYn field.
func (o *GetRecord200ResponseContentInner) SetDelYn(v bool) {
	o.DelYn = &v
}

func (o GetRecord200ResponseContentInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRecord200ResponseContentInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !IsNil(o.AliasId) {
		toSerialize["aliasId"] = o.AliasId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.DomainName) {
		toSerialize["domainName"] = o.DomainName
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.ModifiedDate) {
		toSerialize["modifiedDate"] = o.ModifiedDate
	}
	if !IsNil(o.DefaultYn) {
		toSerialize["defaultYn"] = o.DefaultYn
	}
	if !IsNil(o.ApplyYn) {
		toSerialize["applyYn"] = o.ApplyYn
	}
	if !IsNil(o.AliasYn) {
		toSerialize["aliasYn"] = o.AliasYn
	}
	if !IsNil(o.LbPlatform) {
		toSerialize["lbPlatform"] = o.LbPlatform
	}
	if !IsNil(o.LbYn) {
		toSerialize["lbYn"] = o.LbYn
	}
	if !IsNil(o.DelYn) {
		toSerialize["delYn"] = o.DelYn
	}
	return toSerialize, nil
}

type NullableGetRecord200ResponseContentInner struct {
	value *GetRecord200ResponseContentInner
	isSet bool
}

func (v NullableGetRecord200ResponseContentInner) Get() *GetRecord200ResponseContentInner {
	return v.value
}

func (v *NullableGetRecord200ResponseContentInner) Set(val *GetRecord200ResponseContentInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRecord200ResponseContentInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRecord200ResponseContentInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRecord200ResponseContentInner(val *GetRecord200ResponseContentInner) *NullableGetRecord200ResponseContentInner {
	return &NullableGetRecord200ResponseContentInner{value: val, isSet: true}
}

func (v NullableGetRecord200ResponseContentInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRecord200ResponseContentInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


