/*
ncloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDomain200ResponseContentInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDomain200ResponseContentInner{}

// GetDomain200ResponseContentInner struct for GetDomain200ResponseContentInner
type GetDomain200ResponseContentInner struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	CompleteYn *bool `json:"completeYn,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewGetDomain200ResponseContentInner instantiates a new GetDomain200ResponseContentInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomain200ResponseContentInner() *GetDomain200ResponseContentInner {
	this := GetDomain200ResponseContentInner{}
	return &this
}

// NewGetDomain200ResponseContentInnerWithDefaults instantiates a new GetDomain200ResponseContentInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomain200ResponseContentInnerWithDefaults() *GetDomain200ResponseContentInner {
	this := GetDomain200ResponseContentInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetDomain200ResponseContentInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomain200ResponseContentInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetDomain200ResponseContentInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GetDomain200ResponseContentInner) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetDomain200ResponseContentInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomain200ResponseContentInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetDomain200ResponseContentInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetDomain200ResponseContentInner) SetName(v string) {
	o.Name = &v
}

// GetCompleteYn returns the CompleteYn field value if set, zero value otherwise.
func (o *GetDomain200ResponseContentInner) GetCompleteYn() bool {
	if o == nil || IsNil(o.CompleteYn) {
		var ret bool
		return ret
	}
	return *o.CompleteYn
}

// GetCompleteYnOk returns a tuple with the CompleteYn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomain200ResponseContentInner) GetCompleteYnOk() (*bool, bool) {
	if o == nil || IsNil(o.CompleteYn) {
		return nil, false
	}
	return o.CompleteYn, true
}

// HasCompleteYn returns a boolean if a field has been set.
func (o *GetDomain200ResponseContentInner) HasCompleteYn() bool {
	if o != nil && !IsNil(o.CompleteYn) {
		return true
	}

	return false
}

// SetCompleteYn gets a reference to the given bool and assigns it to the CompleteYn field.
func (o *GetDomain200ResponseContentInner) SetCompleteYn(v bool) {
	o.CompleteYn = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetDomain200ResponseContentInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomain200ResponseContentInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetDomain200ResponseContentInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetDomain200ResponseContentInner) SetStatus(v string) {
	o.Status = &v
}

func (o GetDomain200ResponseContentInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDomain200ResponseContentInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CompleteYn) {
		toSerialize["completeYn"] = o.CompleteYn
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGetDomain200ResponseContentInner struct {
	value *GetDomain200ResponseContentInner
	isSet bool
}

func (v NullableGetDomain200ResponseContentInner) Get() *GetDomain200ResponseContentInner {
	return v.value
}

func (v *NullableGetDomain200ResponseContentInner) Set(val *GetDomain200ResponseContentInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomain200ResponseContentInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomain200ResponseContentInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomain200ResponseContentInner(val *GetDomain200ResponseContentInner) *NullableGetDomain200ResponseContentInner {
	return &NullableGetDomain200ResponseContentInner{value: val, isSet: true}
}

func (v NullableGetDomain200ResponseContentInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomain200ResponseContentInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


