/*
ncloud

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRecord200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRecord200Response{}

// GetRecord200Response struct for GetRecord200Response
type GetRecord200Response struct {
	Content []GetRecord200ResponseContentInner `json:"content,omitempty"`
}

// NewGetRecord200Response instantiates a new GetRecord200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRecord200Response() *GetRecord200Response {
	this := GetRecord200Response{}
	return &this
}

// NewGetRecord200ResponseWithDefaults instantiates a new GetRecord200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRecord200ResponseWithDefaults() *GetRecord200Response {
	this := GetRecord200Response{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *GetRecord200Response) GetContent() []GetRecord200ResponseContentInner {
	if o == nil || IsNil(o.Content) {
		var ret []GetRecord200ResponseContentInner
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecord200Response) GetContentOk() ([]GetRecord200ResponseContentInner, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GetRecord200Response) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []GetRecord200ResponseContentInner and assigns it to the Content field.
func (o *GetRecord200Response) SetContent(v []GetRecord200ResponseContentInner) {
	o.Content = v
}

func (o GetRecord200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRecord200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableGetRecord200Response struct {
	value *GetRecord200Response
	isSet bool
}

func (v NullableGetRecord200Response) Get() *GetRecord200Response {
	return v.value
}

func (v *NullableGetRecord200Response) Set(val *GetRecord200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRecord200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRecord200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRecord200Response(val *GetRecord200Response) *NullableGetRecord200Response {
	return &NullableGetRecord200Response{value: val, isSet: true}
}

func (v NullableGetRecord200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRecord200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


